import type { MotionPreset } from "./types";

export const DEFAULT_PRESETS: readonly MotionPreset[] = Object.freeze([
  {
    id: "preset-sol-premium",
    name: "Sol Premium",
    description: "Identidade clássica do Supermercado Sol com dourado e badge vibrante",
    isBuiltin: true,
    isDefault: true,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
    config: {
      themeSlug: "normal",
      layout: "hero",
      speed: 1,
      exitPreset: "hop-lift",
      logo: {
        position: "top-left",
        size: 68,
        sectorText: "AÇOUGUE",
        sectorTextColor: "#f2c94c",
        sectorTextSize: 13,
        sectorLayout: "column",
      },
      badge: {
        type: "text",
        text: "OFERTA",
        size: 70,
        rotation: 3.5,
        background: "#e21b2d",
        color: "#ffffff",
      },
      background: {
        type: "gradient",
        color: "#080a0e",
        gradientStart: "#141822",
        gradientEnd: "#07090c",
        gradientAngle: 150,
      },
      productCard: {
        style: "transparent",
      },
      pricePhysics: {
        impact: "impact",
        shimmer: true,
        shimmerColor: "gold",
      },
      ambient: {
        speed: 18,
        opacity: 40,
      },
    },
  },
  {
    id: "preset-black-friday-impact",
    name: "Black Friday Cartaz Digital",
    description: "Cartaz digital claro com contraste preto & vermelho, transição Paint Swipe e decorações de alto impacto",
    isBuiltin: true,
    isDefault: true,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
    config: {
      themeSlug: "black-friday",
      layout: "hero",
      speed: 1,
      exitPreset: "paint-swipe",
      logo: {
        position: "top-left",
        size: 72,
        sectorText: "AÇOUGUE",
        sectorTextColor: "#111111",
        sectorTextSize: 13,
        sectorLayout: "column",
      },
      badge: {
        type: "text",
        text: "BLACK FRIDAY",
        size: 70,
        rotation: 3.5,
        background: "#111111",
        color: "#ffffff",
      },
      background: {
        type: "solid",
        color: "#F7F6F2",
        gradientStart: "#FFFFFF",
        gradientEnd: "#F7F6F2",
        gradientAngle: 135,
      },
      productCard: {
        style: "transparent",
      },
      pricePhysics: {
        impact: "impact",
        shimmer: false,
        shimmerColor: "white",
      },
      ambient: {
        speed: 18,
        opacity: 30,
      },
      paintSwipe: {
        direction: "left-to-right",
        colorMode: "dual",
        speed: "normal",
      },
      fx: {
        balloons: {
          enabled: false,
          count: 2,
          speed: "normal",
          opacity: 85,
        },
        priceTag: {
          enabled: false,
          position: "top-right",
        },
        paintStrokes: {
          enabled: true,
          variant: "corners",
        },
        strikeAnimation: {
          enabled: true,
        },
        stamp: {
          enabled: true,
          text: "OFERTA REAL",
          position: "bottom-right",
        },
        confetti: {
          enabled: false,
          count: 18,
          speed: "normal",
        },
        cornerTapes: {
          enabled: false,
          text: "BLACK FRIDAY",
          position: "top-left",
        },
      },
      colorOverrides: {
        enabled: false,
      },
      elementAnimations: {
        nameAnimation: "slide-up",
        priceAnimation: "impact",
        imageAnimation: "float",
        choreography: "staggered",
      },
    },
  },
  {
    id: "preset-clean-direto",
    name: "Clean & Direto",
    description: "Visual minimalista e discreto, sem reflexos metálicos intensos e texto em linha",
    isBuiltin: true,
    isDefault: true,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
    config: {
      themeSlug: "normal",
      layout: "hero",
      speed: 1,
      exitPreset: "fade-out",
      logo: {
        position: "top-left",
        size: 60,
        sectorText: "AÇOUGUE",
        sectorTextColor: "#ffffff",
        sectorTextSize: 12,
        sectorLayout: "row",
      },
      badge: {
        type: "text",
        text: "OFERTA",
        size: 65,
        rotation: 0,
        background: "#252a32",
        color: "#ffffff",
      },
      background: {
        type: "solid",
        color: "#0b0e14",
        gradientStart: "#0b0e14",
        gradientEnd: "#0b0e14",
        gradientAngle: 180,
      },
      productCard: {
        style: "transparent",
      },
      pricePhysics: {
        impact: "smooth",
        shimmer: false,
        shimmerColor: "white",
      },
      ambient: {
        speed: 24,
        opacity: 25,
      },
    },
  },
  {
    id: "preset-motion-suave",
    name: "Motion Suave",
    description: "Animações em velocidade moderada com logo centralizada e transições fluidas",
    isBuiltin: true,
    isDefault: true,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
    config: {
      themeSlug: "normal",
      layout: "duo",
      speed: 1,
      exitPreset: "lift",
      logo: {
        position: "top-center",
        size: 64,
        sectorText: "AÇOUGUE",
        sectorTextColor: "#f2c94c",
        sectorTextSize: 12,
        sectorLayout: "column",
      },
      badge: {
        type: "text",
        text: "OFERTA ESPECIAL",
        size: 70,
        rotation: 2,
        background: "#d9a800",
        color: "#000000",
      },
      background: {
        type: "gradient",
        color: "#0a0c10",
        gradientStart: "#141a24",
        gradientEnd: "#080a0e",
        gradientAngle: 160,
      },
      productCard: {
        style: "transparent",
      },
      pricePhysics: {
        impact: "smooth",
        shimmer: true,
        shimmerColor: "silver",
      },
      ambient: {
        speed: 22,
        opacity: 35,
      },
    },
  },
]);
