import type { MotionPreset } from "./types";

export const DEFAULT_PRESETS: readonly MotionPreset[] = Object.freeze([
  {
    id: "preset-sol-premium",
    name: "Sol Premium",
    description: "Identidade clássica do Supermercado Sol com dourado e badge vibrante",
    isBuiltin: true,
    isDefault: true,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
    config: {
      themeSlug: "normal",
      layout: "hero",
      speed: 1,
      exitPreset: "hop-lift",
      logo: {
        position: "top-left",
        size: 68,
        sectorText: "AÇOUGUE",
        sectorTextColor: "#f2c94c",
        sectorTextSize: 13,
        sectorLayout: "column",
      },
      badge: {
        type: "text",
        text: "OFERTA",
        size: 70,
        rotation: 3.5,
        background: "#e21b2d",
        color: "#ffffff",
      },
      background: {
        type: "gradient",
        color: "#080a0e",
        gradientStart: "#141822",
        gradientEnd: "#07090c",
        gradientAngle: 150,
      },
      productCard: {
        style: "transparent",
      },
      pricePhysics: {
        impact: "impact",
        shimmer: true,
        shimmerColor: "gold",
      },
      ambient: {
        speed: 18,
        opacity: 40,
      },
    },
  },
  {
    id: "preset-black-friday-impact",
    name: "Black Friday Cartaz Digital",
    description: "Cartaz digital claro com contraste preto & vermelho, transição Paint Swipe e decorações de alto impacto",
    isBuiltin: true,
    isDefault: true,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
    config: {
      themeSlug: "black-friday",
      layout: "grid8",
      speed: 1,
      exitPreset: "black-friday-lift",
      logo: {
        position: "top-left",
        size: 156,
        sectorText: "",
        sectorTextColor: "#f2c94c",
        sectorTextSize: 8,
        sectorLayout: "column",
        offsetX: -516,
        offsetY: 178,
        sectorOffsetX: -198,
        sectorOffsetY: -800,
        visible: true,
      },
      subtitle: {
        text: "Qualidade para o seu dia.",
        fontSize: 40,
        offsetX: -293,
        offsetY: -74,
        color: "#111111",
        visible: true,
        showBrush: true,
      },
      badge: {
        text: "",
        rotation: 3.5,
        background: "#e21b2d",
        offsetX: 231,
        offsetY: 368,
        size: 410,
        type: "text",
        visible: false,
      },
      background: {
        type: "solid",
        color: "#F7F6F2",
        gradientStart: "#FFFFFF",
        gradientEnd: "#F7F6F2",
        gradientAngle: 135,
      },
      productCard: {
        style: "transparent",
      },
      pricePhysics: {
        impact: "impact",
        shimmer: true,
        shimmerColor: "gold",
      },
      ambient: {
        speed: 18,
        opacity: 55,
      },
      paintSwipe: {
        direction: "left-to-right",
        colorMode: "dual",
        speed: "normal",
      },
      fx: {
        brushCorners: {
          enabled: true,
          opacity: 100,
        },
        balloons: {
          enabled: false,
          count: 2,
          speed: "normal",
          opacity: 85,
        },
        priceTag: {
          enabled: false,
          position: "top-right",
        },
        paintStrokes: {
          enabled: false,
          variant: "corners",
        },
        strikeAnimation: {
          enabled: true,
        },
        stamp: {
          enabled: false,
          text: "OFERTA REAL",
          position: "bottom-right",
        },
        confetti: {
          enabled: false,
          count: 18,
          speed: "normal",
        },
        cornerTapes: {
          enabled: false,
          text: "BLACK FRIDAY",
          position: "top-left",
        },
        fireSparks: {
          enabled: true,
          intensity: "commercial",
          particleCount: 26,
          speed: 1,
          size: 1,
          bottomGlow: true,
          bottomGlowOpacity: 25,
          maxHeight: 105,
          performance: "normal",
        },
      },
      colorOverrides: {
        enabled: true,
        productName: "#ffffff",
        strikeColor: "#000000",
        background: "#000000",
        price: "#ec6f09",
        currency: "#ec6f09",
        unit: "#ec6f09",
        oldPrice: "#666666",
        capsuleBg: "#000000",
        capsuleText: "#ffffff",
        sectorText: "#000000",
        badgeBg: "#000000",
        badgeText: "#ffffff",
      },
      elementAnimations: {
        nameAnimation: "slide-up",
        priceAnimation: "impact",
        imageAnimation: "float",
        choreography: "staggered",
      },
      layoutTuning: {
        hero: {
          productName: {
            fontSizeOffset: -42,
            x: 278,
            y: -7,
          },
          oldPrice: {
            x: 289,
            y: 29,
          },
          productImage: {
            scale: 0.85,
            x: 31,
            y: 26,
          },
          promotionalPrice: {
            fontSizeOffset: 32,
            x: 276,
            y: 48,
          },
        },
        duo: {
          productImage: {
            x: -10,
            y: -9,
            scale: 0.85,
          },
        },
        trio: {
          productImage: {
            scale: 1,
            x: -44,
            y: 39,
          },
        },
        grid4: {
          productImage: {
            x: -43,
            y: 0,
            scale: 1.3,
          },
        },
        grid8: {
          productImage: {
            x: 28,
            y: 18,
            scale: 1.2,
          },
          promotionalPrice: {
            x: -18,
            y: 76,
            fontSizeOffset: 8,
          },
          oldPrice: {
            x: -17,
            y: 68,
          },
          productName: {
            fontSizeOffset: 18,
            x: -4,
            y: 64,
          },
        },
      },
    },
  },
  {
    id: "preset-clean-direto",
    name: "Clean & Direto",
    description: "Visual minimalista e discreto, sem reflexos metálicos intensos e texto em linha",
    isBuiltin: true,
    isDefault: true,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
    config: {
      themeSlug: "normal",
      layout: "hero",
      speed: 1,
      exitPreset: "fade-out",
      logo: {
        position: "top-left",
        size: 60,
        sectorText: "AÇOUGUE",
        sectorTextColor: "#ffffff",
        sectorTextSize: 12,
        sectorLayout: "row",
      },
      badge: {
        type: "text",
        text: "OFERTA",
        size: 65,
        rotation: 0,
        background: "#252a32",
        color: "#ffffff",
      },
      background: {
        type: "solid",
        color: "#0b0e14",
        gradientStart: "#0b0e14",
        gradientEnd: "#0b0e14",
        gradientAngle: 180,
      },
      productCard: {
        style: "transparent",
      },
      pricePhysics: {
        impact: "smooth",
        shimmer: false,
        shimmerColor: "white",
      },
      ambient: {
        speed: 24,
        opacity: 25,
      },
    },
  },
  {
    id: "preset-motion-suave",
    name: "Motion Suave",
    description: "Animações em velocidade moderada com logo centralizada e transições fluidas",
    isBuiltin: true,
    isDefault: true,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-09-01T00:00:00.000Z",
    config: {
      themeSlug: "normal",
      layout: "duo",
      speed: 1,
      exitPreset: "lift",
      logo: {
        position: "top-center",
        size: 64,
        sectorText: "AÇOUGUE",
        sectorTextColor: "#f2c94c",
        sectorTextSize: 12,
        sectorLayout: "column",
      },
      badge: {
        type: "text",
        text: "OFERTA ESPECIAL",
        size: 70,
        rotation: 2,
        background: "#d9a800",
        color: "#000000",
      },
      background: {
        type: "gradient",
        color: "#0a0c10",
        gradientStart: "#141a24",
        gradientEnd: "#080a0e",
        gradientAngle: 160,
      },
      productCard: {
        style: "transparent",
      },
      pricePhysics: {
        impact: "smooth",
        shimmer: true,
        shimmerColor: "silver",
      },
      ambient: {
        speed: 22,
        opacity: 35,
      },
    },
  },
]);
